### ISSUE TITLE
App-Architecture/app/src/main/java/com/frodo/app/android/core/task/AndroidBackgroundExecutorImpl.java 疑问

### ISSUE THREAD

**Issue by ronanhardiman** [frodoking/GradleAndroid-App-Framework#1]
BackgroundCallRunner
run() 方法里面 多次调用
if (mBackgroundCallTask.isCancelled()) {
                return;
}
这个是实际项目里面的经验么,还是保险起见.
谢谢

**Comment by frodoking** [comment]
线程执行场景的不确定性，所以是基于经验的保险做法
